org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

systemProp.http.proxyHost=21.0.0.19
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_012kwz6jFWsvHuLQuG5fk8cs--claude_code_remote--41d44f
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjAwYTAzNTkyLTM0NGQtNGIzZS1iMTU5LWIyZWE3ODI4MWZlYyIsImlhdCI6MTc3NDE3Mjg2MiwiZXhwIjoxNzc0MTg3MjYyLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxUEY0U0ZrM1N4U20yVmhGSGU0ekw1diIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMTJrd3o2akZXc3ZIdUxRdUc1Zms4Y3MtLWNsYXVkZV9jb2RlX3JlbW90ZS0tNDFkNDRmIiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.t0OMvg4L0VVRWJRr3fUGNrE3duH_UU3iMKsRM_WGvGJZsYccGcpoDLPIV8yH0Qw5oHZHuBfjYPlEGctXJ4qmDg
systemProp.https.proxyHost=21.0.0.19
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_012kwz6jFWsvHuLQuG5fk8cs--claude_code_remote--41d44f
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjAwYTAzNTkyLTM0NGQtNGIzZS1iMTU5LWIyZWE3ODI4MWZlYyIsImlhdCI6MTc3NDE3Mjg2MiwiZXhwIjoxNzc0MTg3MjYyLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxUEY0U0ZrM1N4U20yVmhGSGU0ekw1diIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMTJrd3o2akZXc3ZIdUxRdUc1Zms4Y3MtLWNsYXVkZV9jb2RlX3JlbW90ZS0tNDFkNDRmIiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.t0OMvg4L0VVRWJRr3fUGNrE3duH_UU3iMKsRM_WGvGJZsYccGcpoDLPIV8yH0Qw5oHZHuBfjYPlEGctXJ4qmDg
systemProp.http.nonProxyHosts=localhost|127.0.0.1
